import { db } from './db';
import { supabase } from './supabase';
import { Frequency, Expense } from './types';
import { getTodayStr } from './utils';

// Helper to parse YYYY-MM-DD into a UTC Date object
function parseLocalDate(dateStr: string): Date {
  const [year, month, day] = dateStr.split('-').map(Number);
  return new Date(Date.UTC(year, month - 1, day));
}

// Helper to format Date object into YYYY-MM-DD using UTC
function formatLocalDate(date: Date): string {
  const year = date.getUTCFullYear();
  const month = String(date.getUTCMonth() + 1).padStart(2, '0');
  const day = String(date.getUTCDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

// Returns true if a record was already generated for the current period
function isAlreadyGeneratedForPeriod(
  lastGenDateStr: string,
  frequency: Frequency,
  today: Date
): boolean {
  const last = parseLocalDate(lastGenDateStr);
  switch (frequency) {
    case 'daily':
      return formatLocalDate(last) === formatLocalDate(today);
    case 'weekly': {
      // Same Sunday-anchored calendar week as today
      const weekStart = new Date(today);
      weekStart.setUTCDate(today.getUTCDate() - today.getUTCDay());
      weekStart.setUTCHours(0, 0, 0, 0);
      const weekEnd = new Date(weekStart);
      weekEnd.setUTCDate(weekStart.getUTCDate() + 6);
      weekEnd.setUTCHours(23, 59, 59, 999);
      return last >= weekStart && last <= weekEnd;
    }
    case 'monthly':
      return (
        last.getUTCMonth() === today.getUTCMonth() &&
        last.getUTCFullYear() === today.getUTCFullYear()
      );
    case 'yearly':
      return last.getUTCFullYear() === today.getUTCFullYear();
  }
}

// Generates at most ONE expense per recurring template per period.
// Never backfills history — only creates a record for the current period.
export async function processRecurringExpenses(): Promise<void> {
  const todayStr = getTodayStr();
  const todayDate = parseLocalDate(todayStr);

  const allTemplates = await db.recurringExpenses.toArray();
  const templates = allTemplates.filter(t => t.isActive);

  for (const template of templates) {
    // Skip malformed templates
    if (!template.startDate) continue;

    // Don't generate if the start date hasn't arrived yet
    if (parseLocalDate(template.startDate) > todayDate) continue;

    // Don't generate if already done for this period
    if (
      template.lastGeneratedDate &&
      isAlreadyGeneratedForPeriod(template.lastGeneratedDate, template.frequency, todayDate)
    ) {
      continue;
    }

    // Generate exactly ONE expense for today
    const expense: Expense = {
      id: crypto.randomUUID(),
      amount: template.amount,
      currency: 'EUR',
      date: todayStr,
      categoryId: template.categoryId,
      note: `[Auto] ${template.note || ''}`.trim(),
      createdAt: Date.now(),
      updatedAt: Date.now(),
    };

    // Individual add() so the Dexie creating hook fires and syncs to Supabase
    await db.expenses.add(expense);
    await db.recurringExpenses.update(template.id, { lastGeneratedDate: todayStr });
  }
}

// ─── One-time cleanup ────────────────────────────────────────────────
// Removes stale [Auto] expenses older than 1 month that were generated
// by the old backfill logic, and resets lastGeneratedDate to today so
// processRecurringExpenses doesn't immediately re-generate on the next run.
// Guarded by a localStorage flag — runs exactly once per device.
export async function cleanupAutoGeneratedExpenses(): Promise<void> {
  const CLEANUP_KEY = 'recurringCleanupDone';
  if (localStorage.getItem(CLEANUP_KEY)) return;

  const cutoff = new Date();
  cutoff.setMonth(cutoff.getMonth() - 1);
  const cutoffStr = formatLocalDate(cutoff);

  // Collect IDs of stale [Auto] expenses
  const toDelete = (await db.expenses
    .filter(e => Boolean(e.note?.startsWith('[Auto]')) && e.date < cutoffStr)
    .primaryKeys()) as string[];

  if (toDelete.length > 0) {
    // Remove from local DB (bulkDelete skips hooks intentionally — we handle Supabase below)
    await db.expenses.bulkDelete(toDelete);

    // Remove from Supabase in batches of 100 (best-effort)
    try {
      for (let i = 0; i < toDelete.length; i += 100) {
        const batch = toDelete.slice(i, i + 100);
        await supabase.from('expenses').delete().in('id', batch);
      }
    } catch {
      // Supabase delete failed — local data is already clean, Supabase will reconcile on next full sync
    }
  }

  // Reset lastGeneratedDate to today for all recurring expenses.
  // Individual update() calls so the Dexie updating hook fires and syncs each change to Supabase.
  const todayStr = getTodayStr();
  const allRecurring = await db.recurringExpenses.toArray();
  for (const r of allRecurring) {
    await db.recurringExpenses.update(r.id, { lastGeneratedDate: todayStr });
  }

  localStorage.setItem(CLEANUP_KEY, '1');
}
